apiVersion: v1
data:
  alertmanager.yml: |
    global: 
      resolve_timeout: 1m

    receivers:
    - name: default-receiver

    - name: 'gmail-notifications'
      email_configs:
      - to: example@gmail.com 
        from: example@gmail.com # Update your from mail id here
        smarthost: smtp.gmail.com:587
        auth_username: example@gmail.com # Update your from mail id here
        auth_identity: example@gmail.com # Update your from mail id here
        auth_password: password # Update your app-password here
        send_resolved: true
        headers:
          subject: " Prometheus -  Alert  "
        text: "{{ range .Alerts }} Hi, \n{{ .Annotations.summary }}  \n {{ .Annotations.description }} {{end}} "


    route:
      group_interval: 2m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 2m
      routes:
      - match:
          severity: page
        receiver: 'gmail-notifications'

    templates:
    - /etc/alertmanager/*.tmpl
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: sre
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.27.0
    helm.sh/chart: alertmanager-1.10.0
  name: prometheus-alertmanager
  namespace: sre