apiVersion: v1
data:
  alertmanager.yml: |
    global: 
      resolve_timeout: 1m
      slack_api_url: 'https://hooks.slack.com/services/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'

    receivers:
    - name: default-receiver

    - name: 'slack-notificaions'
      slack_configs:
      - channel: '#alert-sre-tp1' 
        send_resolved: true

    - name: 'gmail-notifications'
      email_configs:
      - to: sreuplimit@gmail.com 
        from: sreuplimit@gmail.com # Update your from mail id here
        smarthost: smtp.gmail.com:587
        auth_username: sreuplimit@gmail.com # Update your from mail id here
        auth_identity: sreuplimit@gmail.com # Update your from mail id here
        auth_password: Password1234Password # Update your app-password here
        send_resolved: true
        headers:
          subject: " Prometheus -  Alert  "
        text: "{{ range .Alerts }} Hi, \n{{ .Annotations.summary }}  \n {{ .Annotations.description }} {{end}} "


    route:
      group_interval: 2m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 2m
      routes:
      - match:
          severity: page
        #receiver: 'gmail-notifications'
        receiver: 'slack-notificaions'

    templates:
    - /etc/alertmanager/*.tmpl
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: sre
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.27.0
    helm.sh/chart: alertmanager-1.10.0
  name: prometheus-alertmanager
  namespace: sre